apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bifrost.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
data:
  config.json: |
    {{- include "bifrost.config" . | nindent 4 }}
